config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/profile', to: 'users#show'
  namespace :profile do
    get 'edit'
    get 'orders'
  end

  get '/dashboard', to: 'dashboard#show'
  namespace :dashboard do
    resources :orders, only: [:index]
    resources :items, only: [:index]
  end

  resources :orders, only: [:index, :show, :create] do
    patch ':order_item_id/fulfill', to: 'order_items#update', as: 'item_fulfill'
  end
  resources :order_items, only: [:update]

  resources :items, only: [:index, :show]
  resources :users, only: [:index, :new, :create, :edit, :show, :update] do 
    resources :orders, only: [:index, :update]
    patch 'enable', to: 'users#update'
    patch 'disable', to: 'users#update'
  end
  
  resources :merchants, only: [:index, :update, :show] do
    resources :orders, only: [:index]
    resources :items, only: [:index, :new, :edit, :create, :update] do
      patch 'enable', to: 'items#update'
      patch 'disable', to: 'items#update'
    end
  end
  
  resources :carts, path: '/cart', only: [:index]
  delete '/cart', to: 'carts#empty'
  delete '/cart/:item_id', to: 'carts#remove'
  patch '/cart/:item_id', to: 'carts#update', as: 'cart_item_quantity'

  # custom error pages
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  def index
    if current_admin?
      @merchants = User.where(role: :merchant).order(:name)
    else
      @merchants = User.where(role: :merchant, active: true).order(:name)
    end
  end

  def show
    render file: 'errors/not_found', status: 404 unless current_user

    @merchant = User.find(params[:id])
    if current_admin?
      @orders = current_user.merchant_orders
      if @merchant.user?
        redirect_to user_path(@merchant.path_keys)
      end
    elsif current_user != @merchant
      render file: 'errors/not_found', status: 404
    end
  end

  private

  helper_method def top_sold_merchants_for_past_month
    User.top_sold_merchants_since(1.month.ago)
  end

  helper_method def top_fulfilled_merchants_for_past_month
    User.top_fulfilled_merchants_since(1.month.ago)
  end

  helper_method def top_fastest_merchants_in_user_state
    User.top_fastest_merchants_in(state: current_user.state)
  end

  helper_method def top_fastest_merchants_in_user_city
    User.top_fastest_merchants_in(city: current_user.city)
  end
end

app/views/merchants/_leaderboard.html.erb
<div id="<%= id %>" class="card float-left m-3" style="width: 25rem;">
  <div class="card-body">
    <h5 class="card-title"><%= title %></h5>
    <% if users.present? %>
      <ul>
        <% users.each do |user| %>
          <li><%= user.name %></li>
        <% end %>
      </ul>
    <% else %>
      <p>(none yet)</p>
    <% end %>
  </div>
</div>

app/views/merchants/index.html.erb
<h1>Merchants</h1>

<div class="leaderboards">
  <h2>Leaderboards</h2>
  <%= render 'leaderboard', id: "most_sold", title: 'Merchants who sold the most items in the past month', users: top_sold_merchants_for_past_month %>
  <%= render 'leaderboard', id: "most_fulfilled", title: 'Merchants who fulfilled non-cancelled orders in the past month', users: top_fulfilled_merchants_for_past_month %>
  <% if current_user.present? %>
    <%= render 'leaderboard', id: "fastest_fulfilled_in_state", title: 'Merchants who have fulfilled items the fastest to your state', users: top_fastest_merchants_in_user_state %>
    <%= render 'leaderboard', id: "fastest_fulfilled_in_city", title: 'Merchants who have fulfilled items the fastest to your city', users: top_fastest_merchants_in_user_city %>
  <% end %>

</div>

<br />
<table>
  <thead>
    <tr>
      <th>Name</th>
      <% if current_admin? %>
      <th>Active</th>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr id="merchant-<%= merchant.id %>">
        <td>
        <% if current_admin? %>
        <%= link_to merchant.name, merchant_path(merchant) %>
        <% else %>
        <%= merchant.name %>
        <% end %>
        </td>
        <% if current_admin? %>
        <td><%= merchant.active %></td>
        <td>
          <% if merchant.active %>
          <%= button_to "Disable", user_path(merchant.path_keys), method: :patch, params: { toggle: :disable } %>
          <% else %>
          <%= button_to "Enable", user_path(merchant.path_keys), method: :patch, params: { toggle: :enable } %>
          <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/merchants/show.html.erb
<h1>Merchant Dashboard</h1>

<p><%= link_to "Edit Profile Data", current_admin? ? edit_user_path(@merchant.path_keys) : profile_edit_path %></p>
<p><%= link_to 'My Items for Sale', current_admin? ? merchant_items_path(@merchant) : dashboard_items_path %>

<div id="stats">
  <div id="inv-stats">
    <h3>Inventory Stats</h3>
    <p>Total Items Sold: <%= number_with_delimiter(@total_items_sold) %></p>
    <p>Represents <%= number_to_percentage(@total_items_pcnt, precision: 1) %> of Inventory</p>
  </div>
  <div id="shipping-stats">
    <h3>Shipping Stats</h3>

    <div id='stats-top-states'>
    <p>Top 3 States:</p>
      <% if @top_3_shipping_states %>
      <ul>
      <% @top_3_shipping_states.each do |state| %>
      <li><%= state %></li>
      <% end %>
      </ul>
      <% else %>
      <p>(none yet)</p>
      <% end %>
    </div>

    <div id='stats-top-cities'>
    <p>Top 3 Cities:</p>
      <% if @top_3_shipping_cities %>
      <ul>
      <% @top_3_shipping_cities.each do |city| %>
      <li><%= city %></li>
      <% end %>
      </ul>
      <% else %>
      (none yet)
      <% end %>
    </div>
  </div>

  <div id='stats-most-active-user'>
  <p>Most Active Buying User:
    <% if @most_active_buyer %>
    <%= @most_active_buyer.name %>, <%= @most_active_buyer.order_count %> orders
    <% else %>
    (none yet)
    <% end %>
  </p>
  </div>

  <div id='stats-biggest-order'>
    <p>Biggest Order:
    <% if @biggest_order %>
    Order #<%= @biggest_order.id %>, worth <%= number_to_currency(@biggest_order.total) %><br/>
    It had <%= number_with_delimiter(@biggest_order.item_count) %> items of yours in the order.
    <% else %>
    (none yet)
    <% end %>
    </p>
  </div>

  <div id='stats-top-buyers'>
  <p>Top Buyers:</p>
    <% if @top_buyers %>
    <ul>
    <% @top_buyers.each do |buyer| %>
    <li><%= buyer.name %>, <%= number_to_currency(buyer.total_spent) %></li>
    <% end %>
    </ul>
    <% else %>
    (none yet)
    <% end %>
  </div>
</div>

<% if @merchant && @merchant.merchant_orders.count > 0 %>
  <% if current_admin? %>
  <%= link_to "Merchant Orders", merchant_orders_path(@merchant) %>
  <% elsif current_user.merchant? %>
  <%= link_to "Merchant Orders", dashboard_orders_path %>
  <% end %>
<% end %>

<% if current_admin? %>
  <% if @merchant.active %>
  <%= button_to "Disable", user_path(@merchant.path_keys), method: :patch, params: { toggle: :disable } %>
  <% else %>
  <%= button_to "Enable", user_path(@merchant.path_keys), method: :patch, params: { toggle: :enable } %>
  <% end %>
  <%= button_to "Upgrade to Merchant", user_path(@merchant.path_keys), method: :patch, params: { toggle: :role } %>
<% end %>