config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/profile', to: 'users#show'
  namespace :profile do
    get 'edit'
    get 'orders'
  end

  get '/dashboard', to: 'dashboard#show'
  namespace :dashboard do
    resources :orders, only: [:index]
    resources :items, only: [:index]
  end

  resources :orders, only: [:index, :show, :create] do
    patch ':order_item_id/fulfill', to: 'order_items#update', as: 'item_fulfill'
  end
  resources :order_items, only: [:update]

  resources :items, only: [:index, :show]
  resources :users, only: [:index, :new, :create, :edit, :show, :update] do 
    resources :orders, only: [:index, :update]
    patch 'enable', to: 'users#update'
    patch 'disable', to: 'users#update'
  end
  
  resources :merchants, only: [:index, :update, :show] do
    resources :orders, only: [:index]
    resources :items, only: [:index, :new, :edit, :create, :update] do
      patch 'enable', to: 'items#update'
      patch 'disable', to: 'items#update'
    end
  end
  
  resources :carts, path: '/cart', only: [:index]
  delete '/cart', to: 'carts#empty'
  delete '/cart/:item_id', to: 'carts#remove'
  patch '/cart/:item_id', to: 'carts#update', as: 'cart_item_quantity'

  # custom error pages
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || Hash.new(0)
  end

  def total_count
    @contents.values.sum
  end

  def add_item(item_id)
    @contents[item_id.to_s] ||= 0
    @contents[item_id.to_s] += 1
  end

  def remove_item(item_id)
    item_id_str = item_id.to_s
    if @contents.key?(item_id_str)
      @contents[item_id.to_s] -= 1
      if @contents[item_id.to_s] <= 0
        @contents.delete(item_id.to_s)
      end
    end
  end

  def remove_all_item(item_id)
    item_id_str = item_id.to_s
    if @contents.key?(item_id_str)
      @contents.delete(item_id.to_s)      
    end
  end

  def count_of(item_id)
    @contents[item_id.to_s].to_i
  end

  def grand_total
    total = 0
    Item.where(id: @contents.keys).each do |item|
      total += (item.price * count_of(item.id))
    end
    total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def index
    @items = Item.where(id: @cart.contents.keys)
  end

  def update
    item = Item.find(params[:item_id])
    if params[:quantity] == 'more'
      if @cart.count_of(item.id)+1 <= item.inventory
        @cart.add_item(item.id)
        flash[:success] = "Added another #{item.name} to your cart"
      else
        flash[:warning] = "Cannot add another #{item.name} to your cart, merchant doesn't have enough inventory"
      end
    elsif params[:quantity] == 'less'
      @cart.remove_item(item.id)
      flash[:success] = "Removed #{item.name} from your cart"
    elsif params[:quantity] == 'none'
      @cart.remove_all_item(item.id)
      flash[:success] = "Removed entire quantity of #{item.name} from your cart"
    end
    session[:cart] = @cart.contents
    redirect_back(fallback_location: items_path)
  end

  def empty
    session[:cart] = nil
    @cart = Cart.new({})
    redirect_to carts_path
  end
end

app/views/carts/index.html.erb
<h1>My Cart</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Subtotal</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr id="item-<%= item.id %>">
        <td><%= link_to item.name, item_path(id: item.slug) %></td>
        <td>
          <img id="item-image-<%= item.id %>" alt="image for <%= item.name %>" src="<%= item.image %>" width="200" />
        </td>
        <td>Merchant: <%= item.user.name %></td>
        <td>Price: <%= item.price %></td>
        <td>Quantity: <%= @cart.count_of(item.id) %></td>
        <td>Subtotal: <%= number_to_currency(item.price * @cart.count_of(item.id)) %></td>
        <td>
          <%= button_to 'Add 1', cart_item_quantity_path(item_id: item.id), method: :patch, params: {quantity: :more} %>
          <%= button_to 'Remove 1', cart_item_quantity_path(item_id: item.id), method: :patch, params: {quantity: :less} %>
          <%= button_to 'Remove All', cart_item_quantity_path(item_id: item.id), method: :patch, params: {quantity: :none} %>
          decrease/remove
          </td>
      </tr>
    <% end %>
    <tr>
      <td colspan=4></td>
      <td>Grand Total: <%= number_to_currency(@cart.grand_total) %></td>
    </tr>
  </tbody>
</table>

<%= button_to 'Empty Cart', cart_path, method: :delete %>

<% if current_user %>
  <%= button_to 'Check out', orders_path, method: :post %>
<% else %>
  <div id="must-log-in">
  You must <%= link_to 'register', register_path %> or
  <%= link_to 'log in', login_path %> to complete your purchase.
  </div>
<% end %>