config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/profile', to: 'users#show'
  namespace :profile do
    get 'edit'
    get 'orders'
  end

  get '/dashboard', to: 'dashboard#show'
  namespace :dashboard do
    resources :orders, only: [:index]
    resources :items, only: [:index]
  end

  resources :orders, only: [:index, :show, :create] do
    patch ':order_item_id/fulfill', to: 'order_items#update', as: 'item_fulfill'
  end
  resources :order_items, only: [:update]

  resources :items, only: [:index, :show]
  resources :users, only: [:index, :new, :create, :edit, :show, :update] do 
    resources :orders, only: [:index, :update]
    patch 'enable', to: 'users#update'
    patch 'disable', to: 'users#update'
  end
  
  resources :merchants, only: [:index, :update, :show] do
    resources :orders, only: [:index]
    resources :items, only: [:index, :new, :edit, :create, :update] do
      patch 'enable', to: 'items#update'
      patch 'disable', to: 'items#update'
    end
  end
  
  resources :carts, path: '/cart', only: [:index]
  delete '/cart', to: 'carts#empty'
  delete '/cart/:item_id', to: 'carts#remove'
  patch '/cart/:item_id', to: 'carts#update', as: 'cart_item_quantity'

  # custom error pages
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :orders, through: :order_items

  validates_presence_of :name, :description
  validates :price, presence: true, numericality: {
    only_integer: false,
    greater_than_or_equal_to: 0
  }
  validates :inventory, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }

  def path_keys
    { id: slug || id }
  end

  def self.slug_find(id)
    find_by!('slug = ? OR id = ?', id, id.to_i)
  end

  def self.popular_items(quantity)
    select('items.*, sum(order_items.quantity) as total_ordered')
      .joins(:orders)
      .where('orders.status != ?', :cancelled)
      .where('order_items.fulfilled = ?', true)
      .group('items.id, order_items.id')
      .order('total_ordered desc')
      .limit(quantity)
  end
end

app/controllers/dashboard/items_controller.rb
class Dashboard::ItemsController < ApplicationController
  def index 
    render file: 'errors/not_found', status: 404 unless current_user
    @items = Item.where(user: current_user)
    render :'items/index'
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
      @items = Item.where(active: true)

      @popular_items = Item.popular_items(5)
      @popular_merchants = User.popular_merchants(5)
      @fastest_merchants = User.fastest_merchants(3)
      @slowest_merchants = User.slowest_merchants(3)
  end

  def new
    @item = Item.new
    @merchant = User.find(params[:merchant_id])
    @form_url = merchant_items_path
  end

  def show
    @item = Item.slug_find(params[:id])
  end

  def edit
    render file: 'errors/not_found', status: 404 if current_user.nil?
    @merchant = User.find(params[:merchant_id])
    render file: 'errors/not_found', status: 404 unless current_admin? || current_user == @merchant
    @item = Item.slug_find(params[:id])
    @form_url = merchant_item_path(@merchant, @item)
  end

  def create
    render file: 'errors/not_found', status: 404 if current_user.nil?
    @merchant = User.find(params[:merchant_id])
    render file: 'errors/not_found', status: 404 unless current_admin? || current_user == @merchant

    @item = @merchant.items.create(item_params)
    if @item.save
      if @item.image.nil? || @item.image.empty?
        @item.image = 'https://picsum.photos/200/300/?image=0&blur=true'
        @item.save
      end
      flash[:success] = "Item created"
      redirect_to current_admin? ? merchant_items_path(@merchant) : dashboard_items_path
    else
      @form_url = merchant_items_path
      render :new
    end
  end

  def update
    render file: 'errors/not_found', status: 404 if current_user.nil?
    @merchant = User.find(params[:merchant_id])
    item_id = :item_id
    if params[:id]
      item_id = :id
    end
    @item = Item.slug_find(params[item_id])
    render file: 'errors/not_found', status: 404 unless current_admin? || current_user == @merchant

    if request.fullpath.split('/')[-1] == 'disable'
      flash[:success] = "Item #{@item.id} is now disabled"
      @item.active = false
      @item.save
      redirect_to current_admin? ? merchant_items_path(@merchant) : dashboard_items_path
    elsif request.fullpath.split('/')[-1] == 'enable'
      flash[:success] = "Item #{@item.id} is now enabled"
      @item.active = true
      @item.save
      redirect_to current_admin? ? merchant_items_path(@merchant) : dashboard_items_path
    else
      @item.update(item_params)
      if @item.save
        flash[:success] = "Item updated"
        redirect_to current_admin? ? merchant_items_path(@merchant) : dashboard_items_path
      else
        @form_url = merchant_item_path(@merchant, @item)
        render :edit
      end
    end
  end


  private
    def item_params
      params.require(:item).permit(:user_id, :name, :description, :image, :price, :inventory, :slug)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for [@merchant, @item], url: @form_url do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, {id: :item_name, required: true} %>
  </div>

  <% if current_admin? %>
    <div class="field">
      <%= f.label :slug %>
      <%= f.text_field :slug, {id: :item_slug, required: true} %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, {id: :item_description, required: true} %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image, id: :item_image %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price, {id: :item_price, required: true, min: 0} %>
  </div>

  <div class="field">
    <%= f.label :inventory %>
    <%= f.number_field :inventory, {id: :item_inventory, required: true, min: 0} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', merchant: @merchant, item: @item %>

app/views/items/index.html.erb
<h1>Items</h1>

<div id="stats">
  <div id="popular-items">
    <div class="card float-left m-3" style="width: 25rem;">
    <div class="card-body">
    <h5 class="card-title">Most Popular Items:</h5>
    <% if @popular_items %>
    <ul>
    <% @popular_items.each do |item| %>
      <li><%= item.name %>, ordered <%= item.total_ordered %> times</li>
    <% end %>
    </ul>
    <% else %>
    <p>(none yet)</p>
    <% end %>
    </div>
  </div>

  <div id="popular-merchants">
    <div class="card float-left m-3" style="width: 25rem;">
    <div class="card-body">
    <h5 class="card-title">Most Popular Merchants:</h5>
    <% if @popular_merchants %>
    <ul>
    <% @popular_merchants.each do |merchant| %>
      <li><%= merchant.name %>, ordered from <%= merchant.total_orders %> times</li>
    <% end %>
    </ul>
    <% else %>
    <p>(none yet)</p>
    <% end %>
  </div>
  </div>

<br style="clear: both;">

  <div id="fastest-merchants">
    <div class="card float-left m-3" style="width: 25rem;">
    <div class="card-body">
    <h5 class="card-title">Fastest Merchants to Fulfill Ordered Items:</h5>
    <% if @fastest_merchants %>
    <ol>
    <% @fastest_merchants.each do |merchant| %>
      <li><%= merchant.name %></li>
    <% end %>
    </ul>
    <% else %>
    <p>(none yet)</p>
    <% end %>
  </div>
  </div>

  <div id="slowest-merchants">
    <div class="card float-left m-3" style="width: 25rem;">
    <div class="card-body">
    <h5 class="card-title">Slowest Merchants to Fulfill Ordered Items:</h5>
    <% if @slowest_merchants %>
    <ol>
    <% @slowest_merchants.each do |merchant| %>
      <li><%= merchant.name %></li>
    <% end %>
    </ul>
    <% else %>
    <p>(none yet)</p>
    <% end %>
  </div>
  </div>
</div>

<br style="clear: both;">

<% if current_user && current_user.merchant? || current_admin? %>
<%= link_to 'Add New Item', new_merchant_item_path(current_user) %>
<% end %>

<hr>

<% @items.each do |item| %>

<div class="card float-left m-3" style="width: 18rem;">
  <a href="<%= item_path(item.path_keys) %>">
  <img class="card-img-top" id="item-image-<%= item.id %>" alt="image for <%= item.name %>" src="<%= item.image %>" width="200" />
  </a>

  <div class="card-body" id="item-<%= item.id %>">
    <h5 class="card-title">
      <%= link_to item.name, item_path(item.path_keys), class: 'card-link' %>
      <% if current_admin? || current_user == item.user %>
      <%= link_to "ID: #{item.id}", item_path(item.path_keys) %>
      <% end %>
    </h5>
    <img class="card-img-top" id="item-image-<%= item.id %>" alt="image for <%= item.name %>" src="<%= item.image %>" width="0" />
    <p>Price: <%= number_to_currency(item.price) %></p>
    <p>
      <strong>Merchant:</strong> <%= item.user.name %><br/>
      <strong>Inventory:</strong> <%= item.inventory %></p>
    <p><em><%= item.description %></em></p>

    <% if current_admin? || current_user && current_user == item.user %>
      <p>Item Active: <%= item.active %></p>
      <p><%= link_to 'Edit Item', edit_merchant_item_path(current_user, item), class: 'card-link' %></p>
      <% if item.active %>
      <%= button_to "Disable Item", merchant_item_disable_path(current_user, item.id), method: :patch, params: { toggle: :disable } %>
      <% else %>
      <%= button_to "Enable Item", merchant_item_enable_path(current_user, item.id), method: :patch, params: { toggle: :enable } %>
      <% end %>
    <% end %>
  </div>
</div>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', merchant: @merchant, item: @item %>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Image:</strong>
  <img id="item-image-<%= @item.id %>" alt="image for <%= @item.name %>" src="<%= @item.image %>" />
</p>

<p>
  <strong>Merchant:</strong>
  <%= @item.user.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Inventory:</strong>
  <%= @item.inventory %>
</p>

<%= button_to 'Add to Cart', cart_item_quantity_path(item_id: @item.id), method: :patch, params: {quantity: :more} %>

<% if current_admin? || current_user == @item.user %>
<%= link_to 'Edit', edit_merchant_item(@item.user, @item) %> |
<% end %>
<%= link_to 'Back', items_path %>