config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/profile', to: 'users#show'
  namespace :profile do
    get 'edit'
    get 'orders'
  end

  get '/dashboard', to: 'dashboard#show'
  namespace :dashboard do
    resources :orders, only: [:index]
    resources :items, only: [:index]
  end

  resources :orders, only: [:index, :show, :create] do
    patch ':order_item_id/fulfill', to: 'order_items#update', as: 'item_fulfill'
  end
  resources :order_items, only: [:update]

  resources :items, only: [:index, :show]
  resources :users, only: [:index, :new, :create, :edit, :show, :update] do 
    resources :orders, only: [:index, :update]
    patch 'enable', to: 'users#update'
    patch 'disable', to: 'users#update'
  end
  
  resources :merchants, only: [:index, :update, :show] do
    resources :orders, only: [:index]
    resources :items, only: [:index, :new, :edit, :create, :update] do
      patch 'enable', to: 'items#update'
      patch 'disable', to: 'items#update'
    end
  end
  
  resources :carts, path: '/cart', only: [:index]
  delete '/cart', to: 'carts#empty'
  delete '/cart/:item_id', to: 'carts#remove'
  patch '/cart/:item_id', to: 'carts#update', as: 'cart_item_quantity'

  # custom error pages
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
          <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <%= link_to 'Items', items_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Merchants', merchants_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Cart: #{@cart.total_count}", carts_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto navbar-right">
    <% if current_user.nil? %>
      <li class="nav-item"><%= link_to 'Log in', login_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Register', register_path, class: 'nav-link' %></li>
    <% else %>
      <li class="nav-item"><a class="nav-link disabled">Logged in as <%= current_user.name %></a></li>
      <li class="nav-item"><%= link_to 'Profile', profile_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Orders', orders_path, class: 'nav-link' %></li>

      <% if current_user.merchant? %>
      <li class="nav-item"><%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %></li>
      <% end %>

      <% if current_admin? %>
      <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %></li>
      <% end %>

      <li class="nav-item"><%= link_to 'Log out', logout_path, class: 'nav-link' %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LittleShopV2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body>
    <%= render "/layouts/nav" %>

    <div class="container">
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <%= yield %>
    </div>
  </body>
</html>